# Site settings
author: Naya Willis
title: My Coding Journey Part 1
header-img: img/home-bg.png
email: greedybrain18@gmail.com
copyright_name: Naya Willis
description: > # this means to ignore newlines until "baseurl:"
  Code Stories 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  greedybrain

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
